### ISSUE TITLE
Chapter Request: Brighton, UK

### ISSUE THREAD

**Issue by HarryMcCarney** [papers-we-love/organizers#76]
Hiya 

# Where
Brighton UK

# Who
[Harry McCarney](https://twitter.com/hmccarney) Founder of [Hack and Craft](https://hackandcraft.com/).  The meetups will be hosted at our [Brighton office.](https://medium.com/@harrymccarney/why-you-still-need-a-physical-office-with-a-distributed-work-model-774c46871647)

There is a lot of interest within H&C and Brighton's tech community in the theoretical aspects of CS. PWL's format seems like a great way to engage subject experts and introduce the local engineering community to the ideas that underpin much of their day to day work. 

# When
Starting in June, with the intention to host a monthly meetup

# Background
I have experience organising other community groups. We ran several meetups in our Berlin office and I help run the Brighton Table Tennis Club. 

My background is in philosophy and cognitive science so I am in interested in the conceptual aspects of CS. A better understanding of the foundations will help us build more stable structures.

**Comment by hakutsuru** [comment]
@HarryMcCarney -- Brighton is setup - https://github.com/papers-we-love/brighton

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

[Seattle, NYC and others are experimenting with online events. If you hold meetings, please keep community safety in mind. Brighton is our first chapter request since the pandemic was declared in March, so it is great to hear from you >_<]

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by HarryMcCarney** [comment]
Hi Sean,

Many thanks, excited to be a part of PWL. First meetup wont be until after
the lock down, probably end of June.

I have setup a meetup group and a twitter
<https://twitter.com/pwlbrighton>account.
I have also updated the readme and code of conduct.

cheers,
Harry
