### ISSUE TITLE
Chapter request: Taipei, Taiwan

### ISSUE THREAD

**Issue by oskarth** [papers-we-love/organizers#77]
# Where

Taipei, Taiwan
 
# Who

Oskar Thoren, (Vac/Status), co-hosted by Yahsin Huang (The Diode Network) and Chih Cheng Liang (Ethereum Foundation).

The meetups will be hosted at TBD location.

There are a bunch of researchers and engineers in Taipei, and PWL's format seems like a great way to engage subject experts and introduce the local engineering community to the ideas that underpin much of their day to day work.

# When

Starting June 11th 7pm, with the intention to host a monthly meetup.

# What

Proposed first agenda:
7:00 pm Introduction (5min)
7:05 pm Oskar on Kademlia (25min)
7:30 pm Discussion (10min)
7:40 pm CC Liang on Undecided (20min)
8:00 pm Discussion (10min)
8:10 pm Mai-Hsuan Kevin on the socialist millionaires’ problem (20min)
8:30 pm Discussion (10min)
8:40 pm Announcements (5min)

# Background

I'm a protocol researcher at https://vac.dev/ and study distributed-systems/P2P/crypto related field. Also enjoy reading CS papers in general, and sometimes summarize them on my own.

CC and Yahsin are also organizers of https://twitter.com/eth_taipei and https://twitter.com/rxctaipei

**Comment by hakutsuru** [comment]
@oskarth -- Taipei is setup - https://github.com/papers-we-love/taipei

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information. Since you have admin access, add other chapter organizers to support your organization.

With abuse and harassment frequently in the (North American) news, we hope every chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by oskarth** [comment]
Thanks @hakutsuru!
