### ISSUE TITLE
Chapter request: Computing Education

### ISSUE THREAD

**Issue by joenash** [papers-we-love/organizers#83]
Hi there!

I'm looking to start a Papers We Love chapter focused specifically on CS education papers (for example, featuring papers from SIGCSE, IITICSE, etc). I'm not sure if this is currently supported, but I'd love for this chapter to not be tied to a particular location, and instead defined by the narrow subject interest. 

**Where:**
Amsterdam, Netherlands -

**Who:**
Me (Joe Nash, @jna_sh on twitter). Hoping to get some interest from fellow Developer Educators across the industry :)

**When:**
Would like to start in January, with Monthly meetups.

**Background:**
I'm currently a developer educator at Twilio, and in the past have worked on the education programs at GitHub and Unity. I care a lot about supporting students in their journey of learning about CS and software development, and have benefitted a lot in my work from the output of CS Edu researchers, and would like to help get their work out to more folks outside of CS Edu academia! 

I have read the Code of conduct and I accept it.

**Comment by hakutsuru** [comment]
> love for this chapter to not be tied to a particular location, and instead defined by the narrow subject interest

@joenash Fairly certain PWL welcome narrow interests. But we do currently label groups by their city/region. Would it be okay to start with this model, as the Amsterdam chapter?

(If most of the organizers and attendees disperse, but the chapter has momentum, we could rename the group, or it could continue with remote-only meetings [which is what some chapters are doing now due to Covid]... Seems we will figure something out when it becomes necessary.)

**Comment by DarrenN** [comment]
👋🏽 Howdy. @joenash are you thinking the meetup will be primarily remote and "pan-EU"?

**Comment by joenash** [comment]
Thanks for the reply and thoughts @hakutsuru! 

> If most of the organizers and attendees disperse

So my only concern with this is that the organizers will never be not-dispersed, if that makes sense. I think I will be the only person involved initially that's based in Amsterdam/The Netherlands. There's some Dutch researchers I'd love to ask to present their work, but I'd be surprised if much of the audience was based in Amsterdam, and the co-orgs I'm hoping to bring in are all in different countries/cities.

> or it could continue with remote-only meetings

It will be remote-only from the start, both due to the dire COVID situation in the Netherlands, but also wanting to involve an international audience from the off. 

So yes to your q @DarrenN! As far as I'm concerned, the only reason location affects this meetup is for timezone accessibility. 

If this doesn't sound like a good fit for the PWL Chapter model, that's totally understandable and no hard feelings if I need to find another way to run the group 💖

**Comment by DarrenN** [comment]
@joenash I think we can accommodate in light of a changing world. I'm not opposed to something like "Papers We Love Edu" or similar.

@zeeshanlakhani do you have any thoughts here?

**Comment by joenash** [comment]
Hey folks 👋 ,
Sorry to bump, just wanted to see if there was an update on whether this might be possible?

**Comment by hakutsuru** [comment]
Organizers discussed this tonight, and I will be creating the chapter repo soon.

**Comment by joenash** [comment]
Thanks for the update @hakutsuru !

**Comment by hakutsuru** [comment]
@joenash -- Edu is setup - https://github.com/papers-we-love/edu

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information. As maintainer, you will be able to add other admins for the repo.

With abuse and harassment recently in the (North American) news, we hope every chapter will embrace our mission to foster open and accepting communities -- please mention your Code of Conduct during events (and revise it as necessary).

Seattle has been active regularly during the pandemic, but most chapters have gone into hibernation until in person meetings are safe again. Remote meetings can be challenging due to the technology, in New York we have used Twitch, but I have seen other meetups use Jitsi and Zoom.

If you have questions or experience to share about logistics, or other topics, the entire community has access to our slack. If you are able to record sessions, they are welcome on youtube, where they could benefit the public.

Please join us -- http://papersweloveslack.herokuapp.com/

We have had regional chapters with special interests in the past, but your plans for this chapter are exciting. We are encouraged to see a new educational venture, and look forward to hearing about your meetings.

Welcome aboard.

**Comment by joenash** [comment]
Thanks so much @hakutsuru and team! And appreciate the context about current goings-on and how other groups are fairing. Will join the Slack and keep y'all updated with our plans.

**Comment by joenash** [comment]
Hey @hakutsuru  👋 
Is it possible to enable GitHub Discussions for the edu repo? Looking for something forum adjacent for communication/discussion between meetings, and Discussions would be pretty ideal, it coming included with the repo. No worries if not, I'm not sure what the billing/org plan requirements are for Discussions nowadays.

**Comment by hakutsuru** [comment]
> Is it possible to enable GitHub Discussions for the edu repo?

I enabled Github Discussions for your project. But I did not click the "Set up discussions" button and set details though. Could you check if you can do this? I believe you should be able to, as admin of the `edu` repo. Let me know if that does not work. Thanks.

**Comment by joenash** [comment]
yep I'm good to go, thanks @hakutsuru!

**Comment by joenash** [comment]
Hey @hakutsuru and co,

PWL Edu has been inactive for a while, following lay offs at the company that gave us the time/space to run it. I'd been hoping to boot it back up, but haven't been able to get momentum behind it. How do you normally handle chapters falling inactive/defunct? I was wondering whether the repo should be archived.

**Comment by DarrenN** [comment]
👋🏽 @joenash - thanks for the heads up! We'll archive the repo for now. If things pick back up let us know!
