### ISSUE TITLE
Oxford

### ISSUE THREAD

**Issue by DarrenN** [papers-we-love/organizers#9]
@hakutsuru who's running the Oxford repo? Their README and CoC need updating.

**Comment by hakutsuru** [comment]
See email "Re: SynBio - Papers we Love" on 2016-03-02 at 01:31.

Here is correspondance that only involved Clint, myself and Oxford organizers:
```
On Sun, Jan 17, 2016, at 02:52 AM, James Scott-Brown wrote:
My GitHub username is jamesscottbrown.


-- 
Regards,

 James Scott-Brown
 james@jamesscottbrown.com

On Thu, Jan 14, 2016, at 08:55 AM, Robert Oppenheimer wrote:
Hi Clint and Sean, 

Great! Thanks for your help. We’re having our first meet-up next
Thursday! 

James Scott-Brown, our IT manager, will send you his GitHub account
shortly. 

Cheers, 

Robbie


On 13 Jan 2016, at 1:28 am, Clint Newsom <clint@paperswelove.org> wrote:

Hi Robert, 

Thanks so much for taking part! We're going to make a PWL repository for
you and your group. Could you send me GitHub username for contact to add
to our team?

Thanks much!

Clint
```

**Comment by DarrenN** [comment]
Okay, @jamesscottbrown hasn't accepted the invitation to join the team and manage this account. Would reach out to him again and if we don't hear back in a bit remove this repo.

**Comment by hakutsuru** [comment]
I could send an email asking about status, but since this group may have lost momentum, we probably have limited opportunities to interact with Oxford.

Which is to say, @zeeshanlakhani thought we should offer introductions. Maybe this should happen, and I can imagine finesse would help make this positive (even if Oxford PWL flounders). What do you think, Zeeshan? Seems you could write them, I could write them, or both.
